### ISSUE TITLE
Infografia_GestionDeProyectos

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ElisabetRD#2]
![Infografia_GestionDeProyectos](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-ElisabetRD/assets/112036625/ee02bbe9-4e30-44c9-9ac1-b12b4ba6073a)

**Comment by MLR062998** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
